#!/usr/bin/bash

# setting up dotfiles
ln -s ~/code/github.com/madsaune/dotfiles/nvim ~/.config/nvim
ln -s ~/code/github.com/madsaune/dotfiles/alacritty ~/.config/alacritty
ln -s ~/code/github.com/madsaune/dotfiles/.bashrc ~/.bashrc
ln -s ~/code/github.com/madsaune/dotfiles/.tmux.conf ~/.tmux.conf

# copy tiny config (NOTE: do not symlink because of passwords)
mkdir ~/.config/tiny
cp ~/code/github.com/madsaune/dotfiles/tiny/config.yml ~/.config/tiny/config.yml


