-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd [[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' ' .. fg .. ' ' .. bg .. ' ' .. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' ' .. group)
end

local Color2 = '#FF7EFF'
local Color6 = '#FF3B3B'
local Color10 = '#FF5370'
local Color13 = '#00ffff'
local Color15 = '#8f93a2'
local Color4 = '#7EFFFF'
local Color3 = '#666666'
local Color19 = '#1d1f28'
local Color21 = '#ffffff'
local Color12 = '#FFFF00'
local Color16 = '#10130b'
local Color0 = ''
local Color20 = '#777777'
local Color1 = '#FFFF7E'
local Color18 = '#232638'
local Color17 = '#200a0e'
local Color5 = '#7FFF00'
local Color7 = '#FF7F00'
local Color8 = '#FF8800'
local Color9 = '#F78C6C'
local Color11 = '#BB77FF'
local Color14 = '#000000'

highlight('Constant', nil, Color0, 'bold')
highlight('Operator', nil, Color1, nil)
highlight('String', nil, Color2, nil)
highlight('Comment', nil, Color3, nil)
highlight('Identifier', nil, Color4, nil)
highlight('Function', nil, Color5, 'italic')
highlight('Conditional', nil, Color6, nil)
highlight('Repeat', nil, Color6, nil)
highlight('Conditional', nil, Color7, nil)
highlight('Type', nil, Color8, nil)
highlight('TSCharacter', nil, Color9, nil)
highlight('Error', nil, Color10, nil)
highlight('Keyword', nil, Color11, nil)
highlight('Number', nil, Color12, nil)
highlight('StatusLine', Color13, Color14, nil)
highlight('WildMenu', Color14, Color15, nil)
highlight('Pmenu', Color14, Color15, nil)
highlight('PmenuSel', Color15, nil, nil)
highlight('PmenuThumb', Color14, Color15, nil)
highlight('DiffAdd', Color16, nil, nil)
highlight('DiffDelete', Color17, nil, nil)
highlight('Normal', Color14, Color15, nil)
highlight('Visual', Color18, nil, nil)
highlight('CursorLine', Color18, nil, nil)
highlight('ColorColumn', Color18, nil, nil)
highlight('SignColumn', Color14, nil, nil)
highlight('LineNr', nil, Color19, nil)
highlight('TabLine', Color14, Color20, nil)
highlight('TabLineSel', Color21, nil, nil)
highlight('TabLineFill', Color14, Color20, nil)
highlight('TSPunctDelimiter', nil, Color15, nil)

link('Macro', 'Function')
link('TSNamespace', 'TSType')
link('TelescopeNormal', 'Normal')
link('Conditional', 'Operator')
link('Whitespace', 'Comment')
link('TSFunction', 'Function')
link('TSRepeat', 'Repeat')
link('TSConditional', 'Conditional')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSNumber', 'Number')
link('TSTagDelimiter', 'Type')
link('Repeat', 'Conditional')
link('TSKeyword', 'Keyword')
link('TSParameterReference', 'TSParameter')
link('TSLabel', 'Type')
link('TSType', 'Type')
link('TSComment', 'Comment')
link('TSOperator', 'Operator')
link('TSTag', 'MyTag')
link('TSFuncMacro', 'Macro')
link('TSProperty', 'TSField')
link('NonText', 'Comment')
link('TSString', 'String')
link('TSField', 'Constant')
link('TSParameter', 'Constant')
link('Operator', 'Keyword')
link('CursorLineNr', 'Identifier')
link('Folded', 'Comment')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSPunctBracket', 'MyTag')
link('TSConstant', 'Constant')
link('TSFloat', 'Number')
