import = [
    # "~/.config/alacritty/themes/everforest_dark.toml"
    "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[env]
TERM = "xterm-256color"

[shell]
program = "/usr/local/bin/tmux"
args = ["-u", "new", "-A", "-s", "worklife"]

[scrolling]
history = 100000

[window]
padding = { x = 5, y = 5 }
decorations = "Full"
dimensions = { columns = 180, lines = 60 }

[font]
size = 14.0
offset.y = 1
normal = { family = "CommitMono", style = "Regular" }
bold = { family = "CommitMono", style = "Bold" }
italic = { family = "CommitMono", style = "Italic" }
bold_italic = { family = "CommitMono", style = "Bold Italic" }

[selection]
save_to_clipboard = true
